import './js/main_start';
import './constants/refs';
import './constants/constants';
import './js/lng';
import './js/pagination';
import './js/modal-film';
import './js/initLoad';
import './js/modal-footer';
import './js/scroll';
import './js/singIn';
// import './js/dark-theme';
import './js/night-theme';
